version: "3.8"
services:
  api:
    image: ssrmed13/student-back:latest
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PORT=3000
    ports:
      - "8080:3000"
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  front:
    image: ssrmed13/student-front:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
